function handleCallback(callback) {
  try {
  callback();
} catch(e){
  console.error("error thrown");
  
}

}
